"""
Dreamcatcher Client — Drop into any agent project
====================================================
Single-file client for the Dreamcatcher inference server.
No dependencies beyond httpx. Copy this file into your agent codebase.

Usage:
    from dreamcatcher_client import LivingMemory

    memory = LivingMemory()
    context = memory.get_context("Help me debug the auth flow")
    # → Returns structured personal context to inject into your LLM's prompt

    memory.save_session(transcript, agent_name="openclaw")
    # → Saves for tonight's consolidation
"""
import json
import httpx
from typing import Optional


class LivingMemory:
    """Client for the Dreamcatcher inference server."""

    def __init__(self, base_url: str = "http://localhost:8420", timeout: float = 30.0):
        self.base_url = base_url.rstrip("/")
        self._client = httpx.Client(timeout=timeout)

    def is_available(self) -> bool:
        try:
            return self._client.get(f"{self.base_url}/health").status_code == 200
        except Exception:
            return False

    def get_context(self, query: str = "", agent_name: str = "agent",
                    max_tokens: int = 512) -> str:
        """Get personalized context to inject into an agent's system prompt."""
        try:
            resp = self._client.post(f"{self.base_url}/context", json={
                "query": query, "agent_name": agent_name, "max_tokens": max_tokens,
            })
            return resp.json().get("response", "") if resp.status_code == 200 else ""
        except Exception:
            return ""

    def get_memories(self, query: str, max_tokens: int = 256) -> list[dict]:
        """Get structured memories as a list of dicts (category, content, confidence)."""
        try:
            resp = self._client.post(f"{self.base_url}/recall", json={
                "query": query, "max_tokens": max_tokens,
            })
            return resp.json().get("memories", []) if resp.status_code == 200 else []
        except Exception:
            return []

    def recall(self, query: str, max_tokens: int = 256) -> str:
        """Ask the memory model a question. Returns text response."""
        try:
            resp = self._client.post(f"{self.base_url}/recall", json={
                "query": query, "max_tokens": max_tokens,
            })
            return resp.json().get("response", "") if resp.status_code == 200 else ""
        except Exception:
            return ""

    def save_session(self, transcript: str, agent_name: str = "agent",
                     extract_now: bool = False) -> Optional[str]:
        """Save a session transcript for nightly consolidation."""
        try:
            resp = self._client.post(f"{self.base_url}/ingest", json={
                "transcript": transcript, "agent_name": agent_name,
                "extract_now": extract_now,
            })
            return resp.json().get("session_id") if resp.status_code == 200 else None
        except Exception:
            return None

    def close(self):
        self._client.close()

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()


# ── Convenience functions ───────────────────────────────────────────

def enhance_system_prompt(system_prompt: str, user_query: str,
                          url: str = "http://localhost:8420") -> str:
    """One-liner to enhance any system prompt with personal memory."""
    with LivingMemory(url) as m:
        if not m.is_available():
            return system_prompt
        ctx = m.get_context(user_query)
        return f"{system_prompt}\n\n{ctx}" if ctx else system_prompt


def generate_claude_md(output_path: str = "CLAUDE.md",
                       url: str = "http://localhost:8420") -> str:
    """Generate a CLAUDE.md memory file for Claude Code / OpenClaw."""
    with LivingMemory(url) as m:
        if not m.is_available():
            return ""
        ctx = m.get_context("comprehensive user profile summary", max_tokens=1024)
        if ctx:
            content = "# Personal Memory\n*Auto-generated by Dreamcatcher*\n\n" + ctx
            with open(output_path, "w") as f:
                f.write(content)
            return content
    return ""


# ── Backward compatibility aliases ─────────────────────────────────
PersonalMemory = LivingMemory
DreamcatcherMemory = LivingMemory
